name: fitness_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase_auth: 0.7.0
  firebase_auth: ^0.11.1+8
  # firebase_database: ^1.1.0+1
  firebase_database: ^3.0.4
  # firebase_storage: ^1.1.0+1
  firebase_storage: ^3.0.3
  # firebase_analytics: ^3.0.1
  # cloud_firestore:
  # flutter_dialogflow: ^0.1.0
  flutter_dialogflow: ^0.1.2
  # googleapis: any
  googleapis: ^0.54.0
  # googleapis_auth: any
  googleapis_auth: ^0.2.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # flutter_custom_clippers: ^0.1.6
  flutter_custom_clippers: ^1.0.4
  # flare_flutter: ^1.0.0
  flare_flutter: ^1.5.4
  # built_mirrors: ^0.10.2
  # import 'package:flutter_vector_icons/flutter_vector_icons.dart';
  flutter_vector_icons: ^0.1.0
  # flutter_sticky_header: ^0.3.4
  # fluro: "^1.4.0"
  # curved_navigation_bar: ^0.1.2
  curved_navigation_bar: ^0.3.0
  # flutter_svg: ^0.12.0
  flutter_svg: ^0.13.1
  flutter_reactive_button: ^1.1.0
  image_picker_modern: ^0.4.12+2
  toast: ^0.1.4
  intl: ^0.15.8
  # random_color: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    # login assets
    - assets/
    # - assets/login_assets/Teddy.flr
    - config/dialogflow.json

    # - bmi images
    - assets/bmi_assets/bmi_images/gender_arrow.svg
    - assets/bmi_assets/bmi_images/gender_female.svg
    - assets/bmi_assets/bmi_images/gender_male.svg
    - assets/bmi_assets/bmi_images/gender_other.svg
    - assets/bmi_assets/bmi_images/pacman.svg
    - assets/bmi_assets/bmi_images/person.svg
    - assets/bmi_assets/bmi_images/user.svg
    - assets/bmi_assets/bmi_images/weight_arrow.svg
    # exercise images
    - assets/exercise_assets/exercise_images/back_down.gif
    - assets/exercise_assets/exercise_images/bhs.gif
    - assets/exercise_assets/exercise_images/chm.gif
    - assets/exercise_assets/exercise_images/clicky_hips.gif
    - assets/exercise_assets/exercise_images/gcm.gif
    - assets/exercise_assets/exercise_images/giphy.gif
    - assets/exercise_assets/exercise_images/hand_ley_up.gif
    - assets/exercise_assets/exercise_images/Ibwd.gif
    - assets/exercise_assets/exercise_images/ibwz.gif
    - assets/exercise_assets/exercise_images/leg.gif
    - assets/exercise_assets/exercise_images/ley_up.gif
    - assets/exercise_assets/exercise_images/right_left.gif
    - assets/exercise_assets/exercise_images/uitn.gif
    - assets/exercise_assets/exercise_images/vel.gif
    - assets/exercise_assets/exercise_images/boxing.gif
    - assets/exercise_assets/exercise_images/bridge.gif
    - assets/exercise_assets/exercise_images/bridge_walk.gif
    - assets/exercise_assets/exercise_images/down.gif
    - assets/exercise_assets/exercise_images/glute_bridge.gif
    - assets/exercise_assets/exercise_images/jumping_heigh.gif
    - assets/exercise_assets/exercise_images/jumping_jacks.gif
    - assets/exercise_assets/exercise_images/jumping_row.gif
    - assets/exercise_assets/exercise_images/jumpint_table.gif
    - assets/exercise_assets/exercise_images/Junu.gif
    - assets/exercise_assets/exercise_images/leg_up_down.gif
    - assets/exercise_assets/exercise_images/lose_belly_fat.gif
    - assets/exercise_assets/exercise_images/one_ball_down.gif
    - assets/exercise_assets/exercise_images/onw_ball_down_back.gif
    - assets/exercise_assets/exercise_images/piti.gif
    - assets/exercise_assets/exercise_images/press_up.gif
    - assets/exercise_assets/exercise_images/row_fetch.gif
    - assets/exercise_assets/exercise_images/seated_rope_low_row.gif
    - assets/exercise_assets/exercise_images/slow_siting.gif
    - assets/exercise_assets/exercise_images/small_weight_carry.gif
    - assets/exercise_assets/exercise_images/squat_juming.gif
    - assets/exercise_assets/exercise_images/streate_jump.gif
    - assets/exercise_assets/exercise_images/two_ball_down.gif
    - assets/exercise_assets/exercise_images/weight_carry.gif
    - assets/exercise_assets/exercise_images/weight_carry_midium.gif
    - assets/exercise_assets/exercise_images/water.jpg

    # foods
    - assets/food_assets/
    - assets/food_assets/low_carb.jpg

    # exercise icons
    - assets/exercise_assets/exercise_icons/reps.png
    - assets/exercise_assets/exercise_icons/set.png

    # - assets/grocery/
    # - assets/grocery_assets/grocery_images/brocoli.png
    # - assets/grocery_assets/grocery_images/cabbage.png
    # - assets/grocery_assets/grocery_images/capsicum.png
    # - assets/grocery_assets/grocery_images/cart_icon.png
    # - assets/grocery_assets/grocery_images/delivery.png
    # - assets/grocery_assets/grocery_images/fruit.png
    # - assets/grocery_assets/grocery_images/home_icon.png
    # - assets/grocery_assets/grocery_images/mango.png
    # - assets/grocery_assets/grocery_images/mango_slice.png
    # - assets/grocery_assets/grocery_images/mortar.png
    # - assets/grocery_assets/grocery_images/pineapple.png
    # - assets/grocery_assets/grocery_images/vegetables.png

    # post images
    - assets/post_assets/post_images/reduce_belly_fat.jpg
    - assets/post_assets/post_images/img-placeholder.jpg

    # chat bot images
    - assets/chat_bot_assets/

    # reactions
    - assets/reaction_images/
    - assets/reaction_images/like.gif
    - assets/reaction_images/love.gif
    - assets/reaction_images/sad.gif
    - assets/reaction_images/wow.gif
    - assets/reaction_images/angry.gif
    - assets/reaction_images/haha.png
    - assets/reaction_images/like.png
    - assets/reaction_images/liker.png
    - assets/reaction_images/love.png
    - assets/reaction_images/sad.png
    - assets/reaction_images/wow.png
    - assets/reaction_images/angry.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # exercise fonts
    - family: Poppins
      fonts:
        - asset: assets/exercise_assets/exercise_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/exercise_assets/exercise_fonts/Poppins-Regular.ttf
          weight: 400
          # login fornts

          # login fonts
    # - family: RobotoMedium
    #   fonts:
    #     - asset: assets/login_assets/fonts/Roboto-Medium.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
